name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      ### Setup

      - name: install lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "stable"

      ### Build

      - name: print version information
        run: |
          make --version
          make version

      - name: print version of fpc
        run: fpc -iW

      - name: start with a clean build
        run: make clean

      # TODO: fix the commented out app to compile again
      # - run: make smartset_adv2
      # - run: make smartset_fsedge
      - run: make smartset_master
      - run: make smartset_master_office
      - run: make smartset_rgb
      # - run: make smartset_savant_elite
      - run: make smartset_tko

      ### Artifact Uploads

      # TODO: these currently just upload the entire directory for each of the
      #       apps, but in the future this can be fine tuned to just upload
      #       the executables instead

      - uses: actions/upload-artifact@v4
        with:
          name: SmartSetAdv2-${{ runner.os }}
          path: SmartSetAdv2

      - uses: actions/upload-artifact@v4
        with:
          name: SmartSetFSEdgePro-${{ runner.os }}
          path: SmartSetFSEdgePro

      - uses: actions/upload-artifact@v4
        with:
          name: SmartSetMaster-${{ runner.os }}
          path: SmartSetMaster

      - uses: actions/upload-artifact@v4
        with:
          name: SmartSetMasterOffice-${{ runner.os }}
          path: SmartSetMasterOffice

      - uses: actions/upload-artifact@v4
        with:
          name: SmartSetSavantElite-${{ runner.os }}
          path: SmartSetSavantElite
